### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by MonsJovis** [citmp2015/flink-visual-programming#10]
* Vorversion bis 9.12.
* Finale Präsentation am 16.12.
* ca. 30  Minuten
* max 4 Personen
* Basic Erklärung - Leute haben grundlegende Flink-Kenntnisse
* Motivation erklären
* Warum Visual Programming
* danach evtl. in drei Gruppen Status zeigen

**Comment by Fabsi110** [comment]
Vision - @Fabsi110
Environment - @whoww 
Back End - @Malcolm-X
Front End - @Neoklosch  
Demonstration - @Neoklosch 
Outlook - @Fabsi110
