### ISSUE TITLE
'Cannot read property flinkUrl of null' when URL and port of flink are not set

### ISSUE THREAD

**Issue by MonsJovis** [citmp2015/flink-visual-programming#185]
Appears on click on 'Run & deploy'.  

![2016-02-09_11-59-45](https://cloud.githubusercontent.com/assets/1517092/12914484/bdb2305c-cf24-11e5-82a5-fcb410a1fd07.png)

**Comment by IwoTens** [comment]
Maybe use these values as the default:
url: http://asok16.cit.tu-berlin.de
port: 8082

**Comment by Neoklosch** [comment]
Fixed in  #194
