### ISSUE TITLE
flinkUrl and flinkPort in datasource test modal?

### ISSUE THREAD

**Issue by MonsJovis** [citmp2015/flink-visual-programming#198]
It doesn't make sense for me. Added with commit 567b8f5fb81f28b7b115fe5936290b03f6d3f557 by @Neoklosch 

![image](https://cloud.githubusercontent.com/assets/1517092/12981104/8b10c7d2-d0df-11e5-93b6-1a7fc0c9fc4e.png)

**Comment by Neoklosch** [comment]
Sorry for that. I removed the path prefix in the csv datasource but not in the text datasource
