### ISSUE TITLE
Continous Integration - Extend Jenkins

### ISSUE THREAD

**Issue by MonsJovis** [citmp2015/flink-visual-programming#21]

**Comment by whoww** [comment]
Extend Jenkins:
* Create badges - http://shields.io/
* Write infos into README.md
* Start jenkins build upon new commits on branches

**Comment by Fabsi110** [comment]
I believe this is done...

**Comment by MonsJovis** [comment]
does jenkins build pull requests too?

**Comment by Fabsi110** [comment]
No, it builds the newest master branch and publishes it under http://asok16.cit.tu-berlin.de:8081/
