### ISSUE TITLE
Implement abstract classes (Components)

### ISSUE THREAD

**Issue by Fabsi110** [citmp2015/flink-visual-programming#23]

**Comment by Fabsi110** [comment]
@danielschroeder25 @Rieprecht @Malcolm-X

**Comment by Fabsi110** [comment]
Is there a update on this issue? This is the blocker of most other backend tasks...

**Comment by Rieprecht** [comment]
Yes, I think tomorrow we can show a first version.

**Comment by Fabsi110** [comment]
:+1:

**Comment by Malcolm-X** [comment]
Mi tinks tis sis not blockering

**Comment by Rieprecht** [comment]
basic abstraxct structure done, further implementations in new issues
