### ISSUE TITLE
Store the graph as JSON in the browsers localStorage

### ISSUE THREAD

**Issue by MonsJovis** [citmp2015/flink-visual-programming#44]

**Comment by Neoklosch** [comment]
I think we should also have a "store graph" button to store the graph localy and import them later on.
We can use the methods to write and read the JSON into the localStorage, but offers a easy solution to store graph permanently.

**Comment by MonsJovis** [comment]
I absolutely agree with you, but I think we sould separate the issues.

**Comment by Neoklosch** [comment]
Jep, agreed.
