### ISSUE TITLE
Beispiel JSON für Wordcount

### ISSUE THREAD

**Issue by Fabsi110** [citmp2015/flink-visual-programming#69]
Basierend auf diesem [Code](https://github.com/apache/flink/blob/master/flink-examples/flink-java-examples/src/main/java/org/apache/flink/examples/java/wordcount/WordCount.java) soll ein JSON erstellt werden, das diesen Code beschreibt.

**Comment by Fabsi110** [comment]
@fb55 schaffst du das bis Sonntag Abend? Also nicht die formale Definition, sondern einfach ein Beispiel für den Wordcount Code... Das wäre echt wichtig, dann hätten alle mal wirklich etwas womit sie arbeiten können...

**Comment by fb55** [comment]
Bin gerade in der Schweiz, und der Richtfunk für unsere Unterkunft ist
gestern zusammengebrochen. Wenn der wieder steht, kann ich gerne was
hochladen.

-- 
– Felix

**Comment by MonsJovis** [comment]
@fb55 geht jetzt vielleicht was?
